name: Main
on:
  push:
    branches: [main]
    paths:
      - 'YukiBot/**'
      - '.github/workflows/main.yml'

  # Allow manual trigger 
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.YUKIBOT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.YUKIBOT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.YUKIBOT_AZURE_SUBSCRIPTION_ID }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/YukiBot
          registryUrl: caswell.azurecr.io
          registryUsername: ${{ secrets.YUKIBOT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.YUKIBOT_REGISTRY_PASSWORD }}
          resourceGroup: Personal
          location: eastus2
          imageToBuild: caswell.azurecr.io/personal/yukibot:${{ github.sha }}
          containerAppName: yuki-bot
          environmentVariables: COSMOS_CONNECTION_STRING=secretref:cosmos-connection-string DISCORD_BOT_TOKEN=secretref:discord-bot-token
